name: Make Windows Python

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      # see https://github.com/microsoft/setup-msbuild
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Where sh
      run: where sh
    - name: Check make
      run: tools/make --version
    - name: remove sh.exe
      run: |
        rm 'C:\Program Files\Git\usr\bin\sh.exe'
        rm 'C:\Program Files\Git\bin\sh.exe'
    - name: Check system
      run: tools/make detect_port
    - name: Add Python binaries to path
      run: echo "$((Get-Item ~).FullName)/AppData/Roaming/Python/Python39/Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
    - name: Install NMake
      run: choco install --verbose nmake
    - name: Build third party
      run: tools/make third_party -j4
    - name: Build C++
      run: tools/make cc -j4
    - name: Build Python
      run: tools/make python -j4
    - name: Test
      run: tools/make test_python -j4
    - name: Create wheel package
      run: tools/make package_python
