name: Make Windows Python

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Add Python binaries to path
      run: echo "$((Get-Item ~).FullName)/AppData/Roaming/Python/Python39/Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Clean sh.exe
      run: |
        where sh
        rm 'C:\Program Files\Git\usr\bin\sh.exe'
        rm 'C:\Program Files\Git\bin\sh.exe'
      shell: bash
    - name: Check make
      run: tools\make --version
    - name: Check system
      run: tools\make detect_port
    - name: Build third party
      run: tools\make third_party -j4
    - name: Build C++
      run: tools\make cc -j4
    - name: Build Python
      run: tools\make python -j4
    - name: Test Python
      run: tools\make test_python -j4
    - name: Create wheel package
      run: tools\make package_python
